In [88]:
import pandas as pd
import numpy as np
from patsy import dmatrix, dmatrices

In [68]:
df = pd.DataFrame({'x': np.arange(1, 5), 'y': [2*i for i in np.arange(1, 5)]})

In [70]:
df['z'] = df.x + df.y

In [71]:
df

x  y   z
0  1  2   3
1  2  4   6
2  3  6   9
3  4  8  12

In [75]:
# Basic design matrix
dmat = dmatrix('x + x**2 + x*y', df)
print(dmat)

[[ 1.  1.  2.  2.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  6. 18.]
 [ 1.  4.  8. 32.]]


In [76]:
dmat_df = pd.DataFrame(dmat)

In [78]:
dmat_df.columns = dmat.design_info.term_names

In [79]:
dmat_df

Intercept    x    y   x:y
0        1.0  1.0  2.0   2.0
1        1.0  2.0  4.0   8.0
2        1.0  3.0  6.0  18.0
3        1.0  4.0  8.0  32.0

In [83]:
# Design matrices
y, x = dmatrices('z ~ x + x:y', df)

In [84]:
y

DesignMatrix with shape (4, 1)
   z
   3
   6
   9
  12
  Terms:
    'z' (column 0)

In [85]:
x

DesignMatrix with shape (4, 3)
  Intercept  x  x:y
          1  1    2
          1  2    8
          1  3   18
          1  4   32
  Terms:
    'Intercept' (column 0)
    'x' (column 1)
    'x:y' (column 2)